# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('business_name', models.CharField(max_length=120)),
                ('street', models.CharField(max_length=120)),
                ('zip_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
            ],
        ),
    ]
