# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesslocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstrace',
            name='latitude',
            field=models.CharField(default='none', max_length=120),
        ),
        migrations.AddField(
            model_name='businesstrace',
            name='longitude',
            field=models.CharField(default='none', max_length=120),
        ),
    ]
