# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesslocation', '0003_auto_20160723_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinesSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('name_type', models.CharField(choices=[('bus', 'Business'), ('pers', 'Personal')], default='Business', max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='BusinessTrace',
        ),
    ]
