# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamine',
            name='housing_total',
        ),
        migrations.RemoveField(
            model_name='datamine',
            name='housing_total_occupied',
        ),
        migrations.RemoveField(
            model_name='datamine',
            name='mortgage_monthly',
        ),
        migrations.RemoveField(
            model_name='datamine',
            name='population_total_female_asian',
        ),
        migrations.RemoveField(
            model_name='datamine',
            name='population_total_female_black',
        ),
        migrations.RemoveField(
            model_name='datamine',
            name='population_total_female_white',
        ),
        migrations.RemoveField(
            model_name='datamine',
            name='population_total_male_asian',
        ),
        migrations.RemoveField(
            model_name='datamine',
            name='population_total_male_black',
        ),
        migrations.RemoveField(
            model_name='datamine',
            name='population_total_male_white',
        ),
        migrations.RemoveField(
            model_name='datamine',
            name='rental_price',
        ),
    ]
