# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationdata', '0002_auto_20160908_2051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataMine',
        ),
    ]
